### ISSUE TITLE
questions about  atmospheric light and transmission maps  in ntire19 challenge

### ISSUE THREAD

**Issue by liang233** [pmm09c/ntire-dehazing#1]
hello，thanks for your work，I want to know how to train atmospheric light and transmission maps?In the dehazing challenge, the atmospheric light and transmission maps  are not be provided, Are you using other datasets in challenge?

**Comment by pmm09c** [comment]
For the challenge, we trained from scratch only using the NTIRE 2019 dataset. We didn't observe a benefit from training the atmospheric light and transmission maps separately.

https://arxiv.org/pdf/1904.09059.pdf

Weights for the challenge results are included in the submission release
