### ISSUE TITLE
pretrained model and Dense-haze dataset

### ISSUE THREAD

**Issue by yl-precious** [pmm09c/ntire-dehazing#2]
Hi, where can I download dense-haze dataset? I don't find them on the NTIRE 2019 Image Dehazing Challenge website. are them not public yet?  and could you provide me your pretrained model. Thank you~

**Comment by pmm09c** [comment]
Not sure if they released it. Pretrained weights are included in the releases.

**Comment by yl-precious** [comment]
emm,,, maybe they will release it soon, thanks again!

**Comment by pmm09c** [comment]
NP, during the challenge all the data was hosted through coda lab, so you could try and reach out that way :
https://competitions.codalab.org/competitions/21163#participate
